#!/usr/bin/env python

import sys
import socket

if __name__ == '__main__':
    if len(sys.argv) > 1:
        result = socket.gethostbyaddr(sys.argv[1])
        print('{0} ({1})'.format(result[0], result[2][0]))
    else:
        print('Please provide a fqdn or IP')
